// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-vFg_pDkXFdzHzCHxmvXR8gZBMgGTRw',
    appId: '1:707524421397:web:edcf8a39fffe3844756b1c',
    messagingSenderId: '707524421397',
    projectId: 'flutterfire-rental-app',
    authDomain: 'flutterfire-rental-app.firebaseapp.com',
    storageBucket: 'flutterfire-rental-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi-RMq6mIDRfNOu3gIgpzLYYkBHUGx0fk',
    appId: '1:707524421397:android:c102953e127d1639756b1c',
    messagingSenderId: '707524421397',
    projectId: 'flutterfire-rental-app',
    storageBucket: 'flutterfire-rental-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ByyE5ZS-U_keDV0ScUCX8QN-UNGlBQY',
    appId: '1:707524421397:ios:9d3dbafe5b3915ef756b1c',
    messagingSenderId: '707524421397',
    projectId: 'flutterfire-rental-app',
    storageBucket: 'flutterfire-rental-app.appspot.com',
    iosClientId: '707524421397-j1ouusvu220u2pllgk9n3e3801nao35c.apps.googleusercontent.com',
    iosBundleId: 'com.jasper.rentals.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ByyE5ZS-U_keDV0ScUCX8QN-UNGlBQY',
    appId: '1:707524421397:ios:9d3dbafe5b3915ef756b1c',
    messagingSenderId: '707524421397',
    projectId: 'flutterfire-rental-app',
    storageBucket: 'flutterfire-rental-app.appspot.com',
    iosClientId: '707524421397-j1ouusvu220u2pllgk9n3e3801nao35c.apps.googleusercontent.com',
    iosBundleId: 'com.jasper.rentals.rentalApp',
  );
}
